name: Icon Review

on:
  pull_request_target:
    paths:
      - 'icons/*.svg'

permissions:
  contents: read

jobs:
  icon-review:
    name: Icon Review
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

    permissions:
      pull-requests: write

    steps:
      - name: Checkout Fork 🛎️
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          path: fork
          persist-credentials: false

      - name: Checkout Original 🛎️
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          path: main
          persist-credentials: false

      - name: Get changed SVG file names 📄
        run: |
          cd main
          svgFiles=$(git diff --no-index ../main ../fork --diff-filter=ACMRTUX --name-only | grep '.svg$' | tr '\n' ' ')
          echo "Changed SVG files: $svgFiles"
          echo "SVG_FILES=${svgFiles}" >> $GITHUB_ENV

      - name: Check SVG colors
        id: color_check
        run: |
          cd main
          set -o pipefail
          npx svg-color-linter --colors material-colors.yml ${{env.SVG_FILES}} > color_check_output.txt

      - name: Color check failed 📢
        if: failure()
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const colorCheckOutput = require('fs').readFileSync('main/color_check_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Review failed 🚨\n\nPlease make sure that all SVG files use only colors from the Material Color Palette. More details:\n\n\`\`\`\n${colorCheckOutput}\n\`\`\`\n\nPlease refer to the [contribution guidelines](https://github.com/material-extensions/vscode-material-icon-theme/blob/main/CONTRIBUTING.md#material-design-colors) for more information.`
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Icon Preview
        run: |
          cd main
          npx svg-icon-review --bigIcon ${{env.SVG_FILES}})

      - name: Install jq ⚙️
        run: sudo apt-get install jq

      - name: Upload PNG ⬆️
        env:
          IMAGE_UPLOAD: ${{ secrets.IMAGE_UPLOAD }}
        id: upload
        run: |
          IMAGE_URL=$(curl --location 'https://freeimage.host/json' --form 'source=@"./main/preview.png"' --form 'type="file"' --form 'action="upload"' --form 'auth_token="${{env.IMAGE_UPLOAD}}"' | jq -r '.image.url')
          echo image_url=$IMAGE_URL >> $GITHUB_ENV
        shell: bash

      - name: Post review in PR ✍️
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const image_url = "${{ env.image_url }}";
            console.log('URL: '+image_url);
            const commentBody = '## Preview \n\nThank you for creating a pull request. This preview shows you how your changes will look on the different themes: \n\n ![Generated Preview](' + image_url + ') \n\n You can find more information how to contribute in the [contribution guidelines](https://github.com/material-extensions/vscode-material-icon-theme/blob/main/CONTRIBUTING.md).';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
